### ISSUE TITLE
Can I get your PGD method code for this paper?

### ISSUE THREAD

**Issue by klchen0112** [ZIB-IOL/fw-rde#2]

**Comment by jmaces** [comment]
There is PGD code for box-constrained RDE in our non-Frank-Wolfe repository: [https://github.com/jmaces/rde](https://github.com/jmaces/rde)

You can use the same code also for other constraints by replacing the respective projection step:
```python
# projected gradient step
xk = some_other_projection(xkold - ls_step * mk)
```
instead of
```python
# projected gradient step
xk = np.clip(xkold - ls_step * mk, 0.0, 1.0)
```

**Comment by klchen0112** [comment]
> There is PGD code for box-constrained RDE in our non-Frank-Wolfe repository: https://github.com/jmaces/rde
> 
> You can use the same code also for other constraints by replacing the respective projection step:
> 
> ```python
> # projected gradient step
> xk = some_other_projection(xkold - ls_step * mk)
> ```
> 
> instead of
> 
> ```python
> # projected gradient step
> xk = np.clip(xkold - ls_step * mk, 0.0, 1.0)
> ```

Thanks
